# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.4.0"

# Tlumí varování Ruby 3.4+ „ostruct will not be part of the default gems“ z rubocop-sketchup.
gem "ostruct"

gem "rubocop", ">= 1.72", "< 2.0"
gem "rubocop-sketchup", "~> 2.1"
