app:
  files:
    upload-dir: ${UPLOAD_DIR:uploads/images}

spring:
  application:
    name: Configurator Backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/configuratordb}
    username: ${DB_USERNAME:configuratoruser}
    password: ${DB_PASSWORD:configuratorpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE "UTC"
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000         # 30 s
      max-lifetime: 600000        # 10 min
      pool-name: configurator-pool
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 130MB

management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/ui-docs

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG

jwt:
  users:
    key: ${JWT_USERS_KEY:eYO3lM2ZbmOICY3rPDIqsTRVNBOf5PtI}
    access-token-expiration-in-minutes: 10
    refresh-token-expiration-in-minutes: 10080  # 7 days (7 * 24 * 60)

cors:
  allowed-origins: >
    http://localhost:5173,
    https://localhost:5173,
    http://localhost:3001,
    https://localhost:3001
