/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/users/api/v1/users/{userId}/password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations["usersChangePassword"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/api/v1/users/me/password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations["usersMeChangePassword"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/api/v1/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["usersPaginatedList"]
    put?: never
    post: operations["usersCreate"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/api/v1/auth/public/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["userAuthLogin"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/users/api/v1/users/{userId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["usersGet"]
    put?: never
    post?: never
    delete: operations["usersDelete"]
    options?: never
    head?: never
    patch: operations["usersPatch"]
    trace?: never
  }
  "/users/api/v1/auth/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getUserRefreshToken"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    UserChangePasswordRequestDto: {
      newPassword: string
      confirmNewPassword: string
    }
    UserMeChangePasswordRequestDto: {
      oldPassword: string
      newPassword: string
      confirmNewPassword: string
    }
    UserCreateRequestDto: {
      firstName: string
      surname: string
      email: string
      name: string
      password: string
      confirmPassword: string
    }
    UserDto: {
      /** Format: uuid */
      id: string
      firstName: string
      surname: string
      email: string
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      modifiedAt: string
    }
    LoginCredentialsDto: {
      email: string
      password: string
    }
    JwtTokenDto: {
      token: string
    }
    UserPatchRequestDto: {
      /** @enum {string} */
      path: "SlashFirstName" | "SlashSurname" | "SlashEmail" | "SlashIsActive"
      value?: Record<string, never>
      /** @enum {string} */
      op: "Replace"
    }
    PaginatedResponseMetaDto: {
      /** Format: int32 */
      pagesTotal: number
      nextPageAfter?: string
      prevPageBefore?: string
    }
    UserPaginatedResponseDto: {
      items: components["schemas"]["UserDto"][]
      pageMetadata: components["schemas"]["PaginatedResponseMetaDto"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = {
  usersChangePassword: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserChangePasswordRequestDto"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content?: never
      }
    }
  }
  usersMeChangePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserMeChangePasswordRequestDto"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content?: never
      }
    }
  }
  usersPaginatedList: {
    parameters: {
      query?: {
        limit?: number
        after?: string
        before?: string
        orderBy?: string[]
        ids?: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["UserPaginatedResponseDto"]
        }
      }
    }
  }
  usersCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreateRequestDto"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["UserDto"]
        }
      }
    }
  }
  userAuthLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginCredentialsDto"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["JwtTokenDto"]
        }
      }
    }
  }
  usersGet: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["UserDto"]
        }
      }
    }
  }
  usersDelete: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content?: never
      }
    }
  }
  usersPatch: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserPatchRequestDto"][]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["UserDto"]
        }
      }
    }
  }
  getUserRefreshToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie: {
        refresh_token: string
      }
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: Record<string, unknown>
        content: {
          "*/*": components["schemas"]["JwtTokenDto"]
        }
      }
    }
  }
}
