@startuml
!theme plain
skinparam shadowing false
skinparam linetype ortho

|Výrobce|
start
:Vytvoření modelu a parametrů ve SketchUpu;
:Export ZIP podkladů;

|Výrobce|
:Nahrání ZIP podkladů\ndo administrační části;

|Výrobce|
:Nastavení produktu,\nparametrů a cenových pravidel;
:Publikace konfigurátoru;
:Vložení konfigurátoru\nna web výrobce;

|Zákazník|
:Otevření webové stránky výrobce;
:Konfigurace výrobku;
:Odeslání poptávky;

|Konfiguruj|
:Uložení poptávky;
:Odeslání e-mailových notifikací;
:Zpřístupnění poptávky\nv administrativní části;

|Výrobce|
:Zpracování poptávky;
stop
@enduml
